### ISSUE TITLE
[README] Need to add `Community Forum`

### ISSUE THREAD

**Issue by amino19** [layer5io/containers-101-workshop#11]
**Description**

<a href="https://github.com/layer5io/containers-101-workshop/blob/master/README.md">README.md</a> is the first file one should read when starting a new project. Our community launched `Discussion forum` for help seekers; needs to publish it officially on README.md for convenience.

### Screenshots

**Current behaviour:**
![image](https://user-images.githubusercontent.com/75872316/123441080-16209200-d5f1-11eb-8cac-0f82770161e6.png)

**Desired behaviour:**
![image](https://user-images.githubusercontent.com/75872316/123440623-9d213a80-d5f0-11eb-8ffd-87ba14c0159b.png)

**Note:**
Need to add only last line for `Community Forum`

**Environment:**
 - OS: any [e.g. Ubuntu]
 - Browser: any [e.g. Chrome, Safari]
 - Version: any [e.g. 22]
 - Device: any [e.g. laptop, iPhone 8]

---
**Reference:**
- Take reference to this <a href="https://github.com/layer5io/layer5/pull/1949">pull request</a>

**Comment by debo19** [comment]
Hey, saw this issue isn't assigned to anyone. Could you please assign it to me?

**Comment by sayantan1413** [comment]
Here you go @debo19 :).

**Comment by debo19** [comment]
Thanks :)

**Comment by sayantan1413** [comment]
hey @debo19 If you're not already a part of the Layer5 Community, I encourage you to join the community, to better engage with the community members - https://layer5.io/community/newcomers.
If you feel stuck anywhere, please free to ping us in the slack channel.

**Comment by amino19** [comment]
@debo19 : Are you working on it? :slightly_smiling_face:

**Comment by debo19** [comment]
@amino19 Yes I just put in a pull request , you could check that :)
