### ISSUE TITLE
Issue Template Updates for Figma link 

### ISSUE THREAD

**Issue by thisiskaransgit** [layer5io/containers-101-workshop#19]
### Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.

### Desired Situation
Each template that has a reference to Figma in its resources section should an invite link added.

### Implementation 
```
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```

**Acceptance Tests**
All references to Figma include the "open invite" link.

---
**Resources**

**Alternatives / Additional Context**

**Comment by depleur** [comment]
Hey, I can try to work on this.

**Comment by Sankhadip-Roy** [comment]
> ### Current Behavior
> The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.
> 
> ### Desired Situation
> Each template that has a reference to Figma in its resources section should an invite link added.
> 
> ### Implementation
> ```
> - 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
> ```
> 
> **Acceptance Tests** All references to Figma include the "open invite" link.
> 
> **Resources**
> 
> **Alternatives / Additional Context**

I think here the implementation link is from meshery ui but it should be of layer5 design.

**Comment by thisiskaransgit** [comment]
@Sankhadip-Roy, you're right, I've updated the issue description. Thank you for pointing out this 

@depleur, go ahead 🚀

**Comment by depleur** [comment]
Hey, I don't see a reference to Figma in this codebase.

**Comment by abhijeetgauravm** [comment]
I want to work on it. Can u assign me? @thisiskaransgit

**Comment by thisiskaransgit** [comment]
@depleur, updates?

**Comment by abhijeetgauravm** [comment]
@thisiskaransgit assign me will do the fixes immediately!

**Comment by abhijeetgauravm** [comment]
@thisiskaransgit as @depleur bhai removed his assignment i have made PR for the issue!
