### ISSUE TITLE
Add standard GitHub Issue templates to this repo.

### ISSUE THREAD

**Issue by leecalcote** [layer5io/containers-101-workshop#3]
This repo (containers-101-workshop) has recently been relocated. It is in need of having GitHub issue templates added to it.

The issue templates can be found here - https://github.com/layer5io/meshery/tree/master/.github/ISSUE_TEMPLATE

The .github/ISSUE_TEMPLATE folders need to be created and yml files copied over.

**Comment by leecalcote** [comment]
@morrme would you like to take a crack at this one?

**Comment by morrme** [comment]
@leecalcote Sure ! Thanks for thinking of me!
